config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews
  end

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  mount_uploader :cover, CoverUploader

  validates_presence_of :title, :description, :isbn
  validates :isbn, uniqueness: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @reviews = Review.where(book_id: @book.id)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :isbn, :cover)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => "form-horizontal book" } do |f| %>

  <% if @book.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :isbn, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :isbn, :class => 'form-control' %>
    </div>
    <%=f.error_span(:isbn) %>
  </div>
  <div class="form-group">
    <%= f.label :cover, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :cover %>
    </div>
    <%=f.error_span(:cover) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="table-responsive">
  <table class="table">
    <% @books.each do |book| %>
      <div class="row">
        <div class="col-md-8">
          <h2><%= link_to book.title, book_path(book) %></h2>
          <p><b>ISBN: </b> <%= book.isbn %>  -  <b>Created at: </b> <%=l book.created_at, format: :short %></p>
          <h3><p><b>Description: </b><%= book.description.truncate(90) %></p></h3>
          <p>
            <% if User.is_admin? current_user %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_book_path(book), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          book_path(book),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            <% end %>
          </p>
        </div>
        <div class="col-md-2">
          <%= image_tag book.cover_url(:thumb) if book.cover? %>
        </div>
      </div>
    <% end %>
  </table>
</div>
<% if User.is_admin? current_user %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_book_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @book.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @book.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:isbn) %>:</strong></dt>
  <dd><%= @book.isbn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cover) %>:</strong></dt>
  <dd><%= image_tag @book.cover %></dd>
</dl>

<% if User.is_admin? current_user %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
                books_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_book_path(@book), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                book_path(@book),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% else %>
  <%= link_to t('.NuevoComentario', :default => t("helpers.links.NuevoComentario")),
                new_book_review_path(@book), :class => 'btn btn-default' %>

<% end %>

<% unless @reviews.blank? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:comment) %></th>
        <th><%= model_class.human_attribute_name(:score) %></th>
        <th><%= model_class.human_attribute_name(:user_id) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.comment %></td>
          <td><%= review.score %></td>
          <td><%= review.user.email %></td>
          <td><%=l review.created_at, format: :short %></td>
            <td>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          book_review_path(@book, review),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :method => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' if (User.is_admin? current_user) %>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_book_review_path(@book, review), :class => 'btn btn-default btn-xs' if Review.my_review?(current_user.id, review) %>
              </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>